logging:
  level:
    root: info

spring:
  datasource:
    # 4 mybatis-plus 动态数据源配置
    dynamic:
      primary: users # 设置默认的数据源或者数据源组，默认值即为 master
      datasource:
        # 订单 orders 数据源配置
        orders:
          url: jdbc:mysql://127.0.0.1:3306/orders?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: root
        # 用户 users 数据源配置
        users:
          url: jdbc:mysql://127.0.0.1:3306/users?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: root
    # Druid 自定已配置
    druid:
      # 过滤器配置
      filter:
        stat: # 配置 StatFilter ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
          log-slow-sql: true # 开启慢查询记录
          slow-sql-millis: 5000 # 慢 SQL 的标准，单位：毫秒
      # StatViewServlet 配置
      stat-view-servlet: # 配置 StatViewServlet ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
        enabled: true # 是否开启 StatViewServlet
        login-username: test # 账号
        login-password: test # 密码

#    # 3 druid 多数据源
#    orders:
#      url: jdbc:mysql://127.0.0.1:3306/test_orders?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password:
#      type: com.alibaba.druid.pool.DruidDataSource # 设置类型为 DruidDataSource
#      # Druid 自定义配置，对应 DruidDataSource 中的 setting 方法的属性
#      min-idle: 0 # 池中维护的最小空闲连接数，默认为 0 个。
#      max-active: 20 # 池中最大连接数，包括闲置和使用中的连接，默认为 8 个。
#    # 用户数据源配置
#    users:
#      url: jdbc:mysql://127.0.0.1:3306/test_users?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password:
#      type: com.alibaba.druid.pool.DruidDataSource # 设置类型为 DruidDataSource
#      # Druid 自定义配置，对应 DruidDataSource 中的 setting 方法的属性
#      min-idle: 0 # 池中维护的最小空闲连接数，默认为 0 个。
#      max-active: 20 # 池中最大连接数，包括闲置和使用中的连接，默认为 8 个。
#    # Druid 自定已配置
#    druid:
#      # 过滤器配置
#      filter:
#        stat: # 配置 StatFilter ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
#          log-slow-sql: true # 开启慢查询记录
#          slow-sql-millis: 5000 # 慢 SQL 的标准，单位：毫秒
#      # StatViewServlet 配置
#      stat-view-servlet: # 配置 StatViewServlet ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
#        enabled: true # 是否开启 StatViewServlet
#        login-username: test # 账号
#        login-password: test # 密码

#    # 1. 基于Druid 单数据源
#    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&socketTimeout=3000
#    username: root # 数据库账号
#    password: root # 数据库密码
#    type: com.alibaba.druid.pool.DruidDataSource # 设置类型为 DruidDataSource
#    # Druid 自定义配置，对应 DruidDataSource 中的 setting 方法的属性
#    druid:
#      min-idle: 0 # 池中维护的最小空闲连接数，默认为 0 个。
#      max-active: 20 # 池中最大连接数，包括闲置和使用中的连接，默认为 8 个。
#      filter:
#        stat: # 配置 StatFilter ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
#          log-slow-sql: true # 开启慢查询记录
#          slow-sql-millis: 5000 # 慢 SQL 的标准，单位：毫秒
#      stat-view-servlet: # 配置 StatViewServlet ，对应文档 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatViewServlet%E9%85%8D%E7%BD%AE
#        enabled: true # 是否开启 StatViewServlet
#        login-username: test # 账号
#        login-password: test # 密码

#    # 2 hikair 多数据源配置
#    orders:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/orders?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&socketTimeout=3000
#      username: root # 数据库账号
#      password: root # 数据库密码
#      # HikariCP 自定义配置，对应 HikariConfig 配置属性类
#      hikari:
#        minimum-idle: 20 # 池中维护的最小空闲连接数，默认为 10 个。
#        maximum-pool-size: 20 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。
#        pool-name: orders
#    users:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/users?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&socketTimeout=3000
#      username: root # 数据库账号
#      password: root # 数据库密码
#      # HikariCP 自定义配置，对应 HikariConfig 配置属性类
#      hikari:
#        minimum-idle: 10 # 池中维护的最小空闲连接数，默认为 10 个。
#        maximum-pool-size: 10 # 池中最大连接数，包括闲置和使用中的连接，默认为 10 个。
#        pool-name: users

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: auto # ID 主键自增
  mapper-locations: classpath*:mapper/*.xml
