logging:
  level:
    root: INFO

spring:
  application:
    name: actuator_local_test

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
        exclude: "prometheus"
#  server:
#    port: 8081
  metrics:
    tags:
      region: "us-east-1"
      stack: "prod"
