logging:
  level:
    root: INFO

spring:
  ai:
    zhipuai:
      api-key: 73d4a4df53cb4e04a3bc41b82aac32d9.FumlME4hjyBF9Mhw
      chat:
        options:
          model: GLM-3-Turbo
          temperature: 0.7
