logging:
  level:
    root: INFO

spring:
  data:
    redis:
      url: redis://localhost:6379
  ai:
    zhipuai:
      api-key: 73d4a4df53cb4e04a3bc41b82aac32d9.FumlME4hjyBF9Mhw
      chat:
        options:
          model: GLM-3-Turbo
          temperature: 0.7
    vectorstore:
      redis:
#        index: default-index
#        initialize-schema: false
#        batching-strategy: TOKEN_COUNT # Optional: Controls how documents are batched for embedding
        index: custom-index
        initialize-schema: true
        prefix: custom-prefix

