logging:
  level:
    root: INFO

spring:
  ai:
    moonshot:
      api-key: sk-7gzbE2rQVj0jP581FMPfs7LUPF9cP94BOIrfjW8H53z6IN41
      chat:
        options:
          model: moonshot-v1-8k
          temperature: 0.7

