logging:
  level:
    root: INFO

spring:
  application:
    name: feign-lb
  cloud:
    zookeeper:
      discovery:
        enabled: true
        prefer-ip-address: true
      connect-string: localhost:2181
